## 实习四：基于SQL实现机器学习的基本概念
> 成员：罗逸龙2000017781  占可盈2000013136  范居令2000012942

In [65]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [66]:
import pymysql 
pymysql.install_as_MySQLdb()
%sql mysql://stu2000017781:stu2000017781@162.105.146.37:43306

In [67]:
%sql use stu2000017781;

 * mysql://stu2000017781:***@162.105.146.37:43306
0 rows affected.

[]

### 练习一：发现数据中隐含的辛普森悖论
#### 任务一：使用纯SQL生成报表，并判断是否存在辛普森悖论

首先需要根据要求生成数据集

In [68]:
%%sql

DROP TABLE IF EXISTS application;

CREATE TABLE application (
  id INT,
  sex VARCHAR(10),
  department VARCHAR(20),
  acception VARCHAR(10)
);

INSERT INTO application (id, sex, department, acception)
VALUES
    (1, 'Female', 'Business School', 'Accepted'),
    (2, 'Female', 'Business School', 'Accepted'),
    (3, 'Female', 'Business School', 'Accepted'),
    (4, 'Female', 'Business School', 'Accepted'),
    (5, 'Female', 'Business School', 'Accepted'),
    (6, 'Female', 'Business School', 'Accepted'),
    (7, 'Female', 'Business School', 'Accepted'),
    (8, 'Female', 'Business School', 'Accepted'),
    (9, 'Female', 'Business School', 'Accepted'),
    (10, 'Female', 'Business School', 'Accepted'),
    (11, 'Female', 'Business School', 'Accepted'),
    (12, 'Female', 'Business School', 'Accepted'),
    (13, 'Female', 'Business School', 'Accepted'),
    (14, 'Female', 'Business School', 'Accepted'),
    (15, 'Female', 'Business School', 'Accepted'),
    (16, 'Female', 'Business School', 'Accepted'),
    (17, 'Female', 'Business School', 'Accepted'),
    (18, 'Female', 'Business School', 'Accepted'),
    (19, 'Female', 'Business School', 'Accepted'),
    (20, 'Female', 'Business School', 'Accepted'),
    (21, 'Female', 'Business School', 'Accepted'),
    (22, 'Female', 'Business School', 'Accepted'),
    (23, 'Female', 'Business School', 'Accepted'),
    (24, 'Female', 'Business School', 'Accepted'),
    (25, 'Female', 'Business School', 'Accepted'),
    (26, 'Female', 'Business School', 'Accepted'),
    (27, 'Female', 'Business School', 'Accepted'),
    (28, 'Female', 'Business School', 'Accepted'),
    (29, 'Female', 'Business School', 'Accepted'),
    (30, 'Female', 'Business School', 'Accepted'),
    (31, 'Female', 'Business School', 'Accepted'),
    (32, 'Female', 'Business School', 'Accepted'),
    (33, 'Female', 'Business School', 'Accepted'),
    (34, 'Female', 'Business School', 'Accepted'),
    (35, 'Female', 'Business School', 'Accepted'),
    (36, 'Female', 'Business School', 'Accepted'),
    (37, 'Female', 'Business School', 'Accepted'),
    (38, 'Female', 'Business School', 'Accepted'),
    (39, 'Female', 'Business School', 'Accepted'),
    (40, 'Female', 'Business School', 'Accepted'),
    (41, 'Female', 'Business School', 'Accepted'),
    (42, 'Female', 'Business School', 'Accepted'),
    (43, 'Female', 'Business School', 'Accepted'),
    (44, 'Female', 'Business School', 'Accepted'),
    (45, 'Female', 'Business School', 'Accepted'),
    (46, 'Female', 'Business School', 'Accepted'),
    (47, 'Female', 'Business School', 'Accepted'),
    (48, 'Female', 'Business School', 'Accepted'),
    (49, 'Female', 'Business School', 'Accepted'),
    (50, 'Female', 'Business School', 'Rejected'),
    (51, 'Female', 'Business School', 'Rejected'),
    (52, 'Female', 'Business School', 'Rejected'),
    (53, 'Female', 'Business School', 'Rejected'),
    (54, 'Female', 'Business School', 'Rejected'),
    (55, 'Female', 'Business School', 'Rejected'),
    (56, 'Female', 'Business School', 'Rejected'),
    (57, 'Female', 'Business School', 'Rejected'),
    (58, 'Female', 'Business School', 'Rejected'),
    (59, 'Female', 'Business School', 'Rejected'),
    (60, 'Female', 'Business School', 'Rejected'),
    (61, 'Female', 'Business School', 'Rejected'),
    (62, 'Female', 'Business School', 'Rejected'),
    (63, 'Female', 'Business School', 'Rejected'),
    (64, 'Female', 'Business School', 'Rejected'),
    (65, 'Female', 'Business School', 'Rejected'),
    (66, 'Female', 'Business School', 'Rejected'),
    (67, 'Female', 'Business School', 'Rejected'),
    (68, 'Female', 'Business School', 'Rejected'),
    (69, 'Female', 'Business School', 'Rejected'),
    (70, 'Female', 'Business School', 'Rejected'),
    (71, 'Female', 'Business School', 'Rejected'),
    (72, 'Female', 'Business School', 'Rejected'),
    (73, 'Female', 'Business School', 'Rejected'),
    (74, 'Female', 'Business School', 'Rejected'),
    (75, 'Female', 'Business School', 'Rejected'),
    (76, 'Female', 'Business School', 'Rejected'),
    (77, 'Female', 'Business School', 'Rejected'),
    (78, 'Female', 'Business School', 'Rejected'),
    (79, 'Female', 'Business School', 'Rejected'),
    (80, 'Female', 'Business School', 'Rejected'),
    (81, 'Female', 'Business School', 'Rejected'),
    (82, 'Female', 'Business School', 'Rejected'),
    (83, 'Female', 'Business School', 'Rejected'),
    (84, 'Female', 'Business School', 'Rejected'),
    (85, 'Female', 'Business School', 'Rejected'),
    (86, 'Female', 'Business School', 'Rejected'),
    (87, 'Female', 'Business School', 'Rejected'),
    (88, 'Female', 'Business School', 'Rejected'),
    (89, 'Female', 'Business School', 'Rejected'),
    (90, 'Female', 'Business School', 'Rejected'),
    (91, 'Female', 'Business School', 'Rejected'),
    (92, 'Female', 'Business School', 'Rejected'),
    (93, 'Female', 'Business School', 'Rejected'),
    (94, 'Female', 'Business School', 'Rejected'),
    (95, 'Female', 'Business School', 'Rejected'),
    (96, 'Female', 'Business School', 'Rejected'),
    (97, 'Female', 'Business School', 'Rejected'),
    (98, 'Female', 'Business School', 'Rejected'),
    (99, 'Female', 'Business School', 'Rejected'),
    (100, 'Female', 'Business School', 'Rejected');

INSERT INTO application (id, sex, department, acception)
VALUES
    (101, 'Male', 'Business School', 'Accepted'),
    (102, 'Male', 'Business School', 'Accepted'),
    (103, 'Male', 'Business School', 'Accepted'),
    (104, 'Male', 'Business School', 'Accepted'),
    (105, 'Male', 'Business School', 'Accepted'),
    (106, 'Male', 'Business School', 'Accepted'),
    (107, 'Male', 'Business School', 'Accepted'),
    (108, 'Male', 'Business School', 'Accepted'),
    (109, 'Male', 'Business School', 'Accepted'),
    (110, 'Male', 'Business School', 'Accepted'),
    (111, 'Male', 'Business School', 'Accepted'),
    (112, 'Male', 'Business School', 'Accepted'),
    (113, 'Male', 'Business School', 'Accepted'),
    (114, 'Male', 'Business School', 'Accepted'),
    (115, 'Male', 'Business School', 'Accepted'),
    (116, 'Male', 'Business School', 'Rejected'),
    (117, 'Male', 'Business School', 'Rejected'),
    (118, 'Male', 'Business School', 'Rejected'),
    (119, 'Male', 'Business School', 'Rejected'),
    (120, 'Male', 'Business School', 'Rejected');
    
INSERT INTO application (id, sex, department, acception)
VALUES
    (121, 'Female', 'Law School', 'Accepted'),
    (122, 'Female', 'Law School', 'Rejected'),
    (123, 'Female', 'Law School', 'Rejected'),
    (124, 'Female', 'Law School', 'Rejected'),
    (125, 'Female', 'Law School', 'Rejected'),
    (126, 'Female', 'Law School', 'Rejected'),
    (127, 'Female', 'Law School', 'Rejected'),
    (128, 'Female', 'Law School', 'Rejected'),
    (129, 'Female', 'Law School', 'Rejected'),
    (130, 'Female', 'Law School', 'Rejected'),
    (131, 'Female', 'Law School', 'Rejected'),
    (132, 'Female', 'Law School', 'Rejected'),
    (133, 'Female', 'Law School', 'Rejected'),
    (134, 'Female', 'Law School', 'Rejected'),
    (135, 'Female', 'Law School', 'Rejected'),
    (136, 'Female', 'Law School', 'Rejected'),
    (137, 'Female', 'Law School', 'Rejected'),
    (138, 'Female', 'Law School', 'Rejected'),
    (139, 'Female', 'Law School', 'Rejected'),
    (140, 'Female', 'Law School', 'Rejected');

-- 插入法学院男生申请数据
INSERT INTO application (id, sex, department, acception)
VALUES
    (141, 'Male', 'Law School', 'Accepted'),
    (142, 'Male', 'Law School', 'Accepted'),
    (143, 'Male', 'Law School', 'Accepted'),
    (144, 'Male', 'Law School', 'Accepted'),
    (145, 'Male', 'Law School', 'Accepted'),
    (146, 'Male', 'Law School', 'Accepted'),
    (147, 'Male', 'Law School', 'Accepted'),
    (148, 'Male', 'Law School', 'Accepted'),
    (149, 'Male', 'Law School', 'Accepted'),
    (150, 'Male', 'Law School', 'Accepted'),
    (151, 'Male', 'Law School', 'Rejected'),
    (152, 'Male', 'Law School', 'Rejected'),
    (153, 'Male', 'Law School', 'Rejected'),
    (154, 'Male', 'Law School', 'Rejected'),
    (155, 'Male', 'Law School', 'Rejected'),
    (156, 'Male', 'Law School', 'Rejected'),
    (157, 'Male', 'Law School', 'Rejected'),
    (158, 'Male', 'Law School', 'Rejected'),
    (159, 'Male', 'Law School', 'Rejected'),
    (160, 'Male', 'Law School', 'Rejected'),
    (161, 'Male', 'Law School', 'Rejected'),
    (162, 'Male', 'Law School', 'Rejected'),
    (163, 'Male', 'Law School', 'Rejected'),
    (164, 'Male', 'Law School', 'Rejected'),
    (165, 'Male', 'Law School', 'Rejected'),
    (166, 'Male', 'Law School', 'Rejected'),
    (167, 'Male', 'Law School', 'Rejected'),
    (168, 'Male', 'Law School', 'Rejected'),
    (169, 'Male', 'Law School', 'Rejected'),
    (170, 'Male', 'Law School', 'Rejected'),
    (171, 'Male', 'Law School', 'Rejected'),
    (172, 'Male', 'Law School', 'Rejected'),
    (173, 'Male', 'Law School', 'Rejected'),
    (174, 'Male', 'Law School', 'Rejected'),
    (175, 'Male', 'Law School', 'Rejected'),
    (176, 'Male', 'Law School', 'Rejected'),
    (177, 'Male', 'Law School', 'Rejected'),
    (178, 'Male', 'Law School', 'Rejected'),
    (179, 'Male', 'Law School', 'Rejected'),
    (180, 'Male', 'Law School', 'Rejected'),
    (181, 'Male', 'Law School', 'Rejected'),
    (182, 'Male', 'Law School', 'Rejected'),
    (183, 'Male', 'Law School', 'Rejected'),
    (184, 'Male', 'Law School', 'Rejected'),
    (185, 'Male', 'Law School', 'Rejected'),
    (186, 'Male', 'Law School', 'Rejected'),
    (187, 'Male', 'Law School', 'Rejected'),
    (188, 'Male', 'Law School', 'Rejected'),
    (189, 'Male', 'Law School', 'Rejected'),
    (190, 'Male', 'Law School', 'Rejected'),
    (191, 'Male', 'Law School', 'Rejected'),
    (192, 'Male', 'Law School', 'Rejected'),
    (193, 'Male', 'Law School', 'Rejected'),
    (194, 'Male', 'Law School', 'Rejected'),
    (195, 'Male', 'Law School', 'Rejected'),
    (196, 'Male', 'Law School', 'Rejected'),
    (197, 'Male', 'Law School', 'Rejected'),
    (198, 'Male', 'Law School', 'Rejected'),
    (199, 'Male', 'Law School', 'Rejected'),
    (200, 'Male', 'Law School', 'Rejected'),
    (201, 'Male', 'Law School', 'Rejected'),
    (202, 'Male', 'Law School', 'Rejected'),
    (203, 'Male', 'Law School', 'Rejected'),
    (204, 'Male', 'Law School', 'Rejected'),
    (205, 'Male', 'Law School', 'Rejected'),
    (206, 'Male', 'Law School', 'Rejected'),
    (207, 'Male', 'Law School', 'Rejected'),
    (208, 'Male', 'Law School', 'Rejected'),
    (209, 'Male', 'Law School', 'Rejected'),
    (210, 'Male', 'Law School', 'Rejected'),
    (211, 'Male', 'Law School', 'Rejected'),
    (212, 'Male', 'Law School', 'Rejected'),
    (213, 'Male', 'Law School', 'Rejected'),
    (214, 'Male', 'Law School', 'Rejected'),
    (215, 'Male', 'Law School', 'Rejected'),
    (216, 'Male', 'Law School', 'Rejected'),
    (217, 'Male', 'Law School', 'Rejected'),
    (218, 'Male', 'Law School', 'Rejected'),
    (219, 'Male', 'Law School', 'Rejected'),
    (220, 'Male', 'Law School', 'Rejected'),
    (221, 'Male', 'Law School', 'Rejected'),
    (222, 'Male', 'Law School', 'Rejected'),
    (223, 'Male', 'Law School', 'Rejected'),
    (224, 'Male', 'Law School', 'Rejected'),
    (225, 'Male', 'Law School', 'Rejected'),
    (226, 'Male', 'Law School', 'Rejected'),
    (227, 'Male', 'Law School', 'Rejected'),
    (228, 'Male', 'Law School', 'Rejected'),
    (229, 'Male', 'Law School', 'Rejected'),
    (230, 'Male', 'Law School', 'Rejected'),
    (231, 'Male', 'Law School', 'Rejected'),
    (232, 'Male', 'Law School', 'Rejected'),
    (233, 'Male', 'Law School', 'Rejected'),
    (234, 'Male', 'Law School', 'Rejected'),
    (235, 'Male', 'Law School', 'Rejected'),
    (236, 'Male', 'Law School', 'Rejected'),
    (237, 'Male', 'Law School', 'Rejected'),
    (238, 'Male', 'Law School', 'Rejected'),
    (239, 'Male', 'Law School', 'Rejected'),
    (240, 'Male', 'Law School', 'Rejected');

 * mysql://stu2000017781:***@162.105.146.37:43306
0 rows affected.
0 rows affected.
100 rows affected.
20 rows affected.
20 rows affected.
100 rows affected.

[]

In [69]:
%%sql 

SELECT 
    '商学院' AS 学院,
    COUNT(CASE WHEN sex = 'Female' THEN 1 END) AS 女生申请人数,
    COUNT(CASE WHEN sex = 'Female' AND acception = 'Accepted' THEN 1 END) AS 女生录取人数,
    ROUND(COUNT(CASE WHEN sex = 'Female' AND acception = 'Accepted' THEN 1 END) / COUNT(CASE WHEN sex = 'Female' THEN 1 END) * 100, 2) AS 女生录取率,
    COUNT(CASE WHEN sex = 'Male' THEN 1 END) AS 男生申请人数,
    COUNT(CASE WHEN sex = 'Male' AND acception = 'Accepted' THEN 1 END) AS 男生录取人数,
    ROUND(COUNT(CASE WHEN sex = 'Male' AND acception = 'Accepted' THEN 1 END) / COUNT(CASE WHEN sex = 'Male' THEN 1 END) * 100, 2) AS 男生录取率,
    COUNT(*) AS 合计申请人数,
    COUNT(CASE WHEN acception = 'Accepted' THEN 1 END) AS 合计录取人数,
    ROUND(COUNT(CASE WHEN acception = 'Accepted' THEN 1 END) / COUNT(*) * 100, 2) AS 合计录取率
FROM application
WHERE department = 'Business School'

UNION

SELECT 
    '法学院' AS 学院,
    COUNT(CASE WHEN sex = 'Female' THEN 1 END) AS 女生申请人数,
    COUNT(CASE WHEN sex = 'Female' AND acception = 'Accepted' THEN 1 END) AS 女生录取人数,
    ROUND(COUNT(CASE WHEN sex = 'Female' AND acception = 'Accepted' THEN 1 END) / COUNT(CASE WHEN sex = 'Female' THEN 1 END) * 100, 2) AS 女生录取率,
    COUNT(CASE WHEN sex = 'Male' THEN 1 END) AS 男生申请人数,
    COUNT(CASE WHEN sex = 'Male' AND acception = 'Accepted' THEN 1 END) AS 男生录取人数,
    ROUND(COUNT(CASE WHEN sex = 'Male' AND acception = 'Accepted' THEN 1 END) / COUNT(CASE WHEN sex = 'Male' THEN 1 END) * 100, 2) AS 男生录取率,
    COUNT(*) AS 合计申请人数,
    COUNT(CASE WHEN acception = 'Accepted' THEN 1 END) AS 合计录取人数,
    ROUND(COUNT(CASE WHEN acception = 'Accepted' THEN 1 END) / COUNT(*) * 100, 2) AS 合计录取率
FROM application
WHERE department = 'Law School'

UNION

SELECT 
    '合计' AS 学院,
    COUNT(CASE WHEN sex = 'Female' THEN 1 END) AS 女生申请人数,
    COUNT(CASE WHEN sex = 'Female' AND acception = 'Accepted' THEN 1 END) AS 女生录取人数,
    ROUND(COUNT(CASE WHEN sex = 'Female' AND acception = 'Accepted' THEN 1 END) / COUNT(CASE WHEN sex = 'Female' THEN 1 END) * 100, 2) AS 女生录取率,
    COUNT(CASE WHEN sex = 'Male' THEN 1 END) AS 男生申请人数,
    COUNT(CASE WHEN sex = 'Male' AND acception = 'Accepted' THEN 1 END) AS 男生录取人数,
    ROUND(COUNT(CASE WHEN sex = 'Male' AND acception = 'Accepted' THEN 1 END) / COUNT(CASE WHEN sex = 'Male' THEN 1 END) * 100, 2) AS 男生录取率,
    COUNT(*) AS 合计申请人数,
    COUNT(CASE WHEN acception = 'Accepted' THEN 1 END) AS 合计录取人数,
    ROUND(COUNT(CASE WHEN acception = 'Accepted' THEN 1 END) / COUNT(*) * 100, 2) AS 合计录取率
FROM application;

 * mysql://stu2000017781:***@162.105.146.37:43306
3 rows affected.

[('商学院', 100, 49, Decimal('49.00'), 20, 15, Decimal('75.00'), 120, 64, Decimal('53.33')),
 ('法学院', 20, 1, Decimal('5.00'), 100, 10, Decimal('10.00'), 120, 11, Decimal('9.17')),
 ('合计', 120, 50, Decimal('41.67'), 120, 25, Decimal('20.83'), 240, 75, Decimal('31.25'))]

可以看到，无论是商学院还是法学院,男生的录取率均高于女生的录取率，但是在整体上，女生的录取率高于男生的录取率，这说明**存在**辛普森悖论。

#### 任务二：
下面计算条件概率，判断是否存在辛普森悖论

In [70]:
%%sql

# P(yes│男生)
SELECT COUNT(*) / (SELECT COUNT(*) FROM application WHERE sex = 'Male') AS P_yes_male
FROM application
WHERE sex = 'Male' AND acception = 'Accepted';

 * mysql://stu2000017781:***@162.105.146.37:43306
1 rows affected.

[(Decimal('0.2083'),)]

In [71]:
%%sql

# P(yes│女生)
SELECT COUNT(*) / (SELECT COUNT(*) FROM application WHERE sex = 'Female') AS P_yes_female
FROM application
WHERE sex = 'Female' AND acception = 'Accepted';

 * mysql://stu2000017781:***@162.105.146.37:43306
1 rows affected.

[(Decimal('0.4167'),)]

In [72]:
%%sql

# P(no│男生)
SELECT COUNT(*) / (SELECT COUNT(*) FROM application WHERE sex = 'Male') AS P_no_male
FROM application
WHERE sex = 'Male' AND acception = 'Rejected';

 * mysql://stu2000017781:***@162.105.146.37:43306
1 rows affected.

[(Decimal('0.7917'),)]

In [73]:
%%sql

# P(no|女生)
SELECT COUNT(*) / (SELECT COUNT(*) FROM application WHERE sex = 'Female') AS P_no_female
FROM application
WHERE sex = 'Female' AND acception = 'Rejected';

 * mysql://stu2000017781:***@162.105.146.37:43306
1 rows affected.

[(Decimal('0.5833'),)]

In [74]:
%%sql

# P(yes│<男生,商学院>)
SELECT COUNT(*) / (SELECT COUNT(*) FROM application WHERE sex = 'Male' AND department = 'Business school') AS P_yes_male_business
FROM application
WHERE sex = 'Male' AND department = 'Business school' AND acception = 'Accepted';

 * mysql://stu2000017781:***@162.105.146.37:43306
1 rows affected.

[(Decimal('0.7500'),)]

In [75]:
%%sql

# P(yes│<女生,商学院>)
SELECT COUNT(*) / (SELECT COUNT(*) FROM application WHERE sex = 'Female' AND department = 'Business school') AS P_yes_female_business
FROM application
WHERE sex = 'Female' AND department = 'Business school' AND acception = 'Accepted';

 * mysql://stu2000017781:***@162.105.146.37:43306
1 rows affected.

[(Decimal('0.4900'),)]

In [76]:
%%sql

# P(yes│<男生,法学院>)
SELECT COUNT(*) / (SELECT COUNT(*) FROM application WHERE sex = 'Male' AND department = 'Law school') AS P_yes_female_business
FROM application
WHERE sex = 'Male' AND department = 'Law school' AND acception = 'Accepted';

 * mysql://stu2000017781:***@162.105.146.37:43306
1 rows affected.

[(Decimal('0.1000'),)]

In [77]:
%%sql

# P(yes│<女生,法学院>)
SELECT COUNT(*) / (SELECT COUNT(*) FROM application WHERE sex = 'Female' AND department = 'Law school') AS P_yes_female_law
FROM application
WHERE sex = 'Female' AND department = 'Law school' AND acception = 'Accepted';

 * mysql://stu2000017781:***@162.105.146.37:43306
1 rows affected.

[(Decimal('0.0500'),)]

In [78]:
%%sql

# P(no│<男生,商学院>)
SELECT COUNT(*) / (SELECT COUNT(*) FROM application WHERE sex = 'Male' AND department = 'Business school') AS P_yes_female_law
FROM application
WHERE sex = 'Male' AND department = 'Business school' AND acception = 'Rejected';

 * mysql://stu2000017781:***@162.105.146.37:43306
1 rows affected.

[(Decimal('0.2500'),)]

In [79]:
%%sql

# P(no│<女生,商学院>) 
SELECT COUNT(*) / (SELECT COUNT(*) FROM application WHERE sex = 'Female' AND department = 'Business school') AS P_no_female_business
FROM application
WHERE sex = 'Female' AND department = 'Business school' AND acception = 'Rejected';

 * mysql://stu2000017781:***@162.105.146.37:43306
1 rows affected.

[(Decimal('0.5100'),)]

In [80]:
%%sql

# P(no│<男生,法学院>)
SELECT COUNT(*) / (SELECT COUNT(*) FROM application WHERE sex = 'Male' AND department = 'Law school') AS P_no_male_law
FROM application
WHERE sex = 'Male' AND department = 'Law school' AND acception = 'Rejected';

 * mysql://stu2000017781:***@162.105.146.37:43306
1 rows affected.

[(Decimal('0.9000'),)]

In [81]:
%%sql

# P(no│<女生,法学院>)
SELECT COUNT(*) / (SELECT COUNT(*) FROM application WHERE sex = 'Female' AND department = 'Law school') AS P_no_female_law
FROM application
WHERE sex = 'Female' AND department = 'Law school' AND acception = 'Rejected';

 * mysql://stu2000017781:***@162.105.146.37:43306
1 rows affected.

[(Decimal('0.9500'),)]

由计算结果我们可以再次看到，P(yes│<男生,商学院>)高于P(yes│<女生,商学院>)，P(yes│<男生,法学院>)高于P(yes│<女生,法学院>)，但是P(yes│<男生>)却低于P(yes│<女生>)，这说明**存在**辛普森悖论。当然我们把yes换成no，P(no│<男生,商学院>)低于P(no│<女生,商学院>)，P(no│<男生,法学院>)低于P(no│<女生,法学院>)，但是P(no│<男生>)却高于P(no│<女生>)，这也说明**存在**辛普森悖论。

### 练习二：KNN分类
这里我们使用威斯康辛乳腺癌数据集

#### 任务一：属性值的预处理

In [82]:
%%sql

# 首先需要在数据库中建表
DROP TABLE IF EXISTS breast_cancer;

CREATE TABLE breast_cancer (
   id INTEGER PRIMARY KEY,
   radius_mean REAL,
   texture_mean REAL,
   perimeter_mean REAL,
   area_mean REAL,
   smoothness_mean REAL,
   compactness_mean REAL,
   concavity_mean REAL,
   concave_points_mean REAL,
   symmetry_mean REAL,
   fractal_dimension_mean REAL,
   radius_se REAL,
   texture_se REAL,
   perimeter_se REAL,
   area_se REAL,
   smoothness_se REAL,
   compactness_se REAL,
   concavity_se REAL,
   concave_points_se REAL,
   symmetry_se REAL,
   fractal_dimension_se REAL,
   radius_worst REAL,
   texture_worst REAL,
   perimeter_worst REAL,
   area_worst REAL,
   smoothness_worst REAL,
   compactness_worst REAL,
   concavity_worst REAL,
   concave_points_worst REAL,
   symmetry_worst REAL,
   fractal_dimension_worst REAL,
   diagnosis BOOLEAN
);

 * mysql://stu2000017781:***@162.105.146.37:43306
0 rows affected.
0 rows affected.

[]

In [83]:
user_name = 'stu2000017781'
password = 'stu2000017781'
db_name = 'stu2000017781'

db = pymysql.connect(host='162.105.146.37',user=user_name, password=password,
port=43306,db=db_name)
cursor = db.cursor()

In [84]:
#导入乳腺癌数据
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np

data = load_breast_cancer()

x = data.data
y = data.target
# name = ['平均半径','平均纹理','平均周长','平均面积','平均光滑度',
#         '平均紧凑度','平均凹度','平均凹点','平均对称','平均分形维数',
#         '半径误差','纹理误差','周长误差','面积误差','平滑度误差',
#         '紧凑度误差','凹度误差','凹点误差','对称误差','分形维数误差',
#         '最差半径','最差纹理','最差的边界','最差的区域','最差的平滑度',
#         '最差的紧凑性','最差的凹陷','最差的凹点','最差的对称性','最差的分形维数',
#         '患病否']
insert_query="INSERT INTO breast_cancer (id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean, symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave_points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst,diagnosis) \
 VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
for i in range(x.shape[0]):
    values=(i, x[i][0],x[i][1],x[i][2],x[i][3],x[i][4],x[i][5],x[i][6],x[i][7],x[i][8],x[i][9],x[i][10],x[i][11],x[i][12],x[i][13],x[i][14],x[i][15],x[i][16],x[i][17],x[i][18],x[i][19],x[i][20],x[i][21],x[i][22],x[i][23],x[i][24],x[i][25],x[i][26],x[i][27],x[i][28],x[i][29],y[i])
    try:
        cursor.execute(insert_query, values)
        db.commit()
    except:
        db.rollback()

In [85]:
%%sql

select * from breast_cancer limit 10;

 * mysql://stu2000017781:***@162.105.146.37:43306
10 rows affected.

[(0, 17.99, 10.38, 122.8, 1001.0, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871, 1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193, 25.38, 17.33, 184.6, 2019.0, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189, 0),
 (1, 20.57, 17.77, 132.9, 1326.0, 0.08474, 0.07864, 0.0869, 0.07017, 0.1812, 0.05667, 0.5435, 0.7339, 3.398, 74.08, 0.005225, 0.01308, 0.0186, 0.0134, 0.01389, 0.003532, 24.99, 23.41, 158.8, 1956.0, 0.1238, 0.1866, 0.2416, 0.186, 0.275, 0.08902, 0),
 (2, 19.69, 21.25, 130.0, 1203.0, 0.1096, 0.1599, 0.1974, 0.1279, 0.2069, 0.05999, 0.7456, 0.7869, 4.585, 94.03, 0.00615, 0.04006, 0.03832, 0.02058, 0.0225, 0.004571, 23.57, 25.53, 152.5, 1709.0, 0.1444, 0.4245, 0.4504, 0.243, 0.3613, 0.08758, 0),
 (3, 11.42, 20.38, 77.58, 386.1, 0.1425, 0.2839, 0.2414, 0.1052, 0.2597, 0.09744, 0.4956, 1.156, 3.445, 27.23, 0.00911, 0.07458, 0.05661, 0.01867, 0.05963, 0.009208, 14.91, 26.5, 98.87, 567.7, 0.2098, 0.8663, 0.6869, 0.2575, 0.6638, 0.173, 0),
 (4, 20.29, 14.34, 135.1, 1297.0, 0.1003, 0.1328, 0.198, 0.1043, 0.1809, 0.05883, 0.7572, 0.7813, 5.438, 94.44, 0.01149, 0.02461, 0.05688, 0.01885, 0.01756, 0.005115, 22.54, 16.67, 152.2, 1575.0, 0.1374, 0.205, 0.4, 0.1625, 0.2364, 0.07678, 0),
 (5, 12.45, 15.7, 82.57, 477.1, 0.1278, 0.17, 0.1578, 0.08089, 0.2087, 0.07613, 0.3345, 0.8902, 2.217, 27.19, 0.00751, 0.03345, 0.03672, 0.01137, 0.02165, 0.005082, 15.47, 23.75, 103.4, 741.6, 0.1791, 0.5249, 0.5355, 0.1741, 0.3985, 0.1244, 0),
 (6, 18.25, 19.98, 119.6, 1040.0, 0.09463, 0.109, 0.1127, 0.074, 0.1794, 0.05742, 0.4467, 0.7732, 3.18, 53.91, 0.004314, 0.01382, 0.02254, 0.01039, 0.01369, 0.002179, 22.88, 27.66, 153.2, 1606.0, 0.1442, 0.2576, 0.3784, 0.1932, 0.3063, 0.08368, 0),
 (7, 13.71, 20.83, 90.2, 577.9, 0.1189, 0.1645, 0.09366, 0.05985, 0.2196, 0.07451, 0.5835, 1.377, 3.856, 50.96, 0.008805, 0.03029, 0.02488, 0.01448, 0.01486, 0.005412, 17.06, 28.14, 110.6, 897.0, 0.1654, 0.3682, 0.2678, 0.1556, 0.3196, 0.1151, 0),
 (8, 13.0, 21.82, 87.5, 519.8, 0.1273, 0.1932, 0.1859, 0.09353, 0.235, 0.07389, 0.3063, 1.002, 2.406, 24.32, 0.005731, 0.03502, 0.03553, 0.01226, 0.02143, 0.003749, 15.49, 30.73, 106.2, 739.3, 0.1703, 0.5401, 0.539, 0.206, 0.4378, 0.1072, 0),
 (9, 12.46, 24.04, 83.97, 475.9, 0.1186, 0.2396, 0.2273, 0.08543, 0.203, 0.08243, 0.2976, 1.599, 2.039, 23.94, 0.007149, 0.07217, 0.07743, 0.01432, 0.01789, 0.01008, 15.09, 40.68, 97.65, 711.4, 0.1853, 1.058, 1.105, 0.221, 0.4366, 0.2075, 0)]

为了将除了id与diagnosis之外的属性值转化为[0, 1]之间的数值，另一方面数据的极差相较于数据于最小值的差值不大，因此我们使用最小-最大规范化。

In [86]:
%%sql

SET @min_radius_mean = (SELECT MIN(radius_mean) from breast_cancer);
SET @max_radius_mean = (SELECT MAX(radius_mean) from breast_cancer);
SET @min_texture_mean = (SELECT MIN(texture_mean) from breast_cancer);
SET @max_texture_mean = (SELECT MAX(texture_mean) from breast_cancer);
SET @min_perimeter_mean = (SELECT MIN(perimeter_mean) from breast_cancer);
SET @max_perimeter_mean = (SELECT MAX(perimeter_mean) from breast_cancer);
SET @min_area_mean = (SELECT MIN(area_mean) from breast_cancer);
SET @max_area_mean = (SELECT MAX(area_mean) from breast_cancer);
SET @min_smoothness_mean = (SELECT MIN(smoothness_mean) from breast_cancer);
SET @max_smoothness_mean = (SELECT MAX(smoothness_mean) from breast_cancer);
SET @min_compactness_mean = (SELECT MIN(compactness_mean) from breast_cancer);
SET @max_compactness_mean = (SELECT MAX(compactness_mean) from breast_cancer);
SET @min_concavity_mean = (SELECT MIN(concavity_mean) from breast_cancer);
SET @max_concavity_mean = (SELECT MAX(concavity_mean) from breast_cancer);
SET @min_concave_points_mean = (SELECT MIN(concave_points_mean) from breast_cancer);
SET @max_concave_points_mean = (SELECT MAX(concave_points_mean) from breast_cancer);
SET @min_symmetry_mean = (SELECT MIN(symmetry_mean) from breast_cancer);
SET @max_symmetry_mean = (SELECT MAX(symmetry_mean) from breast_cancer);
SET @min_fractal_dimension_mean = (SELECT MIN(fractal_dimension_mean) from breast_cancer);
SET @max_fractal_dimension_mean = (SELECT MAX(fractal_dimension_mean) from breast_cancer);
SET @min_radius_se = (SELECT MIN(radius_se) from breast_cancer);
SET @max_radius_se = (SELECT MAX(radius_se) from breast_cancer);
SET @min_texture_se = (SELECT MIN(texture_se) from breast_cancer);
SET @max_texture_se = (SELECT MAX(texture_se) from breast_cancer);
SET @min_perimeter_se = (SELECT MIN(perimeter_se) from breast_cancer);
SET @max_perimeter_se = (SELECT MAX(perimeter_se) from breast_cancer);
SET @min_area_se = (SELECT MIN(area_se) from breast_cancer);
SET @max_area_se = (SELECT MAX(area_se) from breast_cancer);
SET @min_smoothness_se = (SELECT MIN(smoothness_se) from breast_cancer);
SET @max_smoothness_se = (SELECT MAX(smoothness_se) from breast_cancer);
SET @min_compactness_se = (SELECT MIN(compactness_se) from breast_cancer);
SET @max_compactness_se = (SELECT MAX(compactness_se) from breast_cancer);
SET @min_concavity_se = (SELECT MIN(concavity_se) from breast_cancer);
SET @max_concavity_se = (SELECT MAX(concavity_se) from breast_cancer);
SET @min_concave_points_se = (SELECT MIN(concave_points_se) from breast_cancer);
SET @max_concave_points_se = (SELECT MAX(concave_points_se) from breast_cancer);
SET @min_symmetry_se = (SELECT MIN(symmetry_se) from breast_cancer);
SET @max_symmetry_se = (SELECT MAX(symmetry_se) from breast_cancer);
SET @min_fractal_dimension_se = (SELECT MIN(fractal_dimension_se) from breast_cancer);
SET @max_fractal_dimension_se = (SELECT MAX(fractal_dimension_se) from breast_cancer);
SET @min_radius_worst = (SELECT MIN(radius_worst) from breast_cancer);
SET @max_radius_worst = (SELECT MAX(radius_worst) from breast_cancer);
SET @min_texture_worst = (SELECT MIN(texture_worst) from breast_cancer);
SET @max_texture_worst = (SELECT MAX(texture_worst) from breast_cancer);
SET @min_perimeter_worst = (SELECT MIN(perimeter_worst) from breast_cancer);
SET @max_perimeter_worst = (SELECT MAX(perimeter_worst) from breast_cancer);
SET @min_area_worst = (SELECT MIN(area_worst) from breast_cancer);
SET @max_area_worst = (SELECT MAX(area_worst) from breast_cancer);
SET @min_smoothness_worst = (SELECT MIN(smoothness_worst) from breast_cancer);
SET @max_smoothness_worst = (SELECT MAX(smoothness_worst) from breast_cancer);
SET @min_compactness_worst = (SELECT MIN(compactness_worst) from breast_cancer);
SET @max_compactness_worst = (SELECT MAX(compactness_worst) from breast_cancer);
SET @min_concavity_worst = (SELECT MIN(concavity_worst) from breast_cancer);
SET @max_concavity_worst = (SELECT MAX(concavity_worst) from breast_cancer);
SET @min_concave_points_worst = (SELECT MIN(concave_points_worst) from breast_cancer);
SET @max_concave_points_worst = (SELECT MAX(concave_points_worst) from breast_cancer);
SET @min_symmetry_worst = (SELECT MIN(symmetry_worst) from breast_cancer);
SET @max_symmetry_worst = (SELECT MAX(symmetry_worst) from breast_cancer);
SET @min_fractal_dimension_worst = (SELECT MIN(fractal_dimension_worst) from breast_cancer);
SET @max_fractal_dimension_worst = (SELECT MAX(fractal_dimension_worst) from breast_cancer);

 * mysql://stu2000017781:***@162.105.146.37:43306
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.

[]

In [87]:
%%sql

UPDATE breast_cancer
SET 
    radius_mean = (radius_mean - @min_radius_mean) / (@max_radius_mean - @min_radius_mean),
    texture_mean = (texture_mean - @min_texture_mean) / (@max_texture_mean - @min_texture_mean),
    perimeter_mean = (perimeter_mean - @min_perimeter_mean) / (@max_perimeter_mean - @min_perimeter_mean),
    area_mean = (area_mean - @min_area_mean) / (@max_area_mean - @min_area_mean),
    smoothness_mean = (smoothness_mean - @min_smoothness_mean) / (@max_smoothness_mean - @min_smoothness_mean),
    compactness_mean = (compactness_mean - @min_compactness_mean) / (@max_compactness_mean - @min_compactness_mean),
    concavity_mean = (concavity_mean - @min_concavity_mean) / (@max_concavity_mean - @min_concavity_mean),
    concave_points_mean = (concave_points_mean - @min_concave_points_mean) / (@max_concave_points_mean - @min_concave_points_mean),
    symmetry_mean = (symmetry_mean - @min_symmetry_mean) / (@max_symmetry_mean - @min_symmetry_mean),
    fractal_dimension_mean = (fractal_dimension_mean - @min_fractal_dimension_mean) / (@max_fractal_dimension_mean - @min_fractal_dimension_mean),
    radius_se = (radius_se - @min_radius_se) / (@max_radius_se - @min_radius_se),
    texture_se = (texture_se - @min_texture_se) / (@max_texture_se - @min_texture_se),
    perimeter_se = (perimeter_se - @min_perimeter_se) / (@max_perimeter_se - @min_perimeter_se),
    area_se = (area_se - @min_area_se) / (@max_area_se - @min_area_se),
    smoothness_se = (smoothness_se - @min_smoothness_se) / (@max_smoothness_se - @min_smoothness_se),
    compactness_se = (compactness_se - @min_compactness_se) / (@max_compactness_se - @min_compactness_se),
    concavity_se = (concavity_se - @min_concavity_se) / (@max_concavity_se - @min_concavity_se),
    concave_points_se = (concave_points_se - @min_concave_points_se) / (@max_concave_points_se - @min_concave_points_se),
    symmetry_se = (symmetry_se - @min_symmetry_se) / (@max_symmetry_se - @min_symmetry_se),
    fractal_dimension_se = (fractal_dimension_se - @min_fractal_dimension_se) / (@max_fractal_dimension_se - @min_fractal_dimension_se),
    radius_worst = (radius_worst - @min_radius_worst) / (@max_radius_worst - @min_radius_worst),
    texture_worst = (texture_worst - @min_texture_worst) / (@max_texture_worst - @min_texture_worst),
    perimeter_worst = (perimeter_worst - @min_perimeter_worst) / (@max_perimeter_worst - @min_perimeter_worst),
    area_worst = (area_worst - @min_area_worst) / (@max_area_worst - @min_area_worst),
    smoothness_worst = (smoothness_worst - @min_smoothness_worst) / (@max_smoothness_worst - @min_smoothness_worst),
    compactness_worst = (compactness_worst - @min_compactness_worst) / (@max_compactness_worst - @min_compactness_worst),
    concavity_worst = (concavity_worst - @min_concavity_worst) / (@max_concavity_worst - @min_concavity_worst),
    concave_points_worst = (concave_points_worst - @min_concave_points_worst) / (@max_concave_points_worst - @min_concave_points_worst),
    symmetry_worst = (symmetry_worst - @min_symmetry_worst) / (@max_symmetry_worst - @min_symmetry_worst),
    fractal_dimension_worst = (fractal_dimension_worst - @min_fractal_dimension_worst) / (@max_fractal_dimension_worst - @min_fractal_dimension_worst);

 * mysql://stu2000017781:***@162.105.146.37:43306
569 rows affected.

[]

In [88]:
%%sql

select * from breast_cancer limit 10;

 * mysql://stu2000017781:***@162.105.146.37:43306
10 rows affected.

[(0, 0.5210374366983767, 0.022658099425092997, 0.5459885287817012, 0.3637327677624602, 0.5937528211609642, 0.7920372983252562, 0.7031396438612932, 0.7311133200795229, 0.6863636363636364, 0.6055181128896379, 0.35614702154626104, 0.12046941301272983, 0.3690335956273854, 0.2738112581668217, 0.15929564537512322, 0.3513984438369334, 0.13568181818181818, 0.30062511839363515, 0.3116451848933416, 0.1830424388154167, 0.6207755247242974, 0.1415245202558635, 0.6683101748095025, 0.4506979944946913, 0.6011358383411478, 0.6192915563058473, 0.5686102236421725, 0.9120274914089348, 0.5984624482554701, 0.4188639643185098, 0),
 (1, 0.6431444933503716, 0.2725735542779844, 0.6157832907193699, 0.5015906680805938, 0.28987993138936535, 0.18176798969388383, 0.2036082474226804, 0.34875745526838964, 0.3797979797979798, 0.14132266217354678, 0.15643671917436175, 0.08258928571428571, 0.12444046553267682, 0.12565978953974424, 0.11938674915864973, 0.0813230390242437, 0.04696969696969697, 0.2538359537791249, 0.0845387516181685, 0.09111009770186422, 0.6069014585556741, 0.3035714285714286, 0.5398177200059765, 0.43521431380259534, 0.34755332496863234, 0.15456335923780692, 0.1929712460063898, 0.6391752577319588, 0.2335895919574217, 0.2228781319690411, 0),
 (2, 0.6014955748024045, 0.39026039905309434, 0.5957432105590491, 0.4494167550371156, 0.5143089284102195, 0.4310165020550886, 0.46251171508903466, 0.6356858846918491, 0.5095959595959596, 0.21124684077506325, 0.22962158247329348, 0.09430251060820369, 0.18037035291900297, 0.16292178902423993, 0.15083115205493422, 0.28395469702887016, 0.09676767676767677, 0.38984656184883504, 0.20569032475938534, 0.1270055138675843, 0.5563856278904304, 0.3600746268656717, 0.5084416554609293, 0.3745084545812033, 0.48358977745492965, 0.38537512976491933, 0.35974440894568693, 0.8350515463917526, 0.40370589394835404, 0.21343303161484986, 0),
 (3, 0.21009039708457572, 0.36083868785931683, 0.23350148573008084, 0.10290562036055144, 0.8113207547169811, 0.8113612661799889, 0.5656044985941893, 0.5228628230616302, 0.7762626262626262, 1.0, 0.13909107369183413, 0.1758751768033946, 0.126655044055977, 0.03815479325660537, 0.2514532413230445, 0.5432150689458347, 0.14295454545454545, 0.3536654669444971, 0.7281476895367817, 0.28720478697676993, 0.24831020988971897, 0.3859275053304905, 0.2413466806115843, 0.09400806134486828, 0.9154724955424947, 0.814011700672352, 0.5486421725239616, 0.8848797250859107, 1.0, 0.773711137347501, 0),
 (4, 0.6298925647214729, 0.15657761244504562, 0.6309861101513371, 0.4892895015906681, 0.43035117811681867, 0.34789276731488866, 0.4639175257731959, 0.5183896620278331, 0.37828282828282833, 0.18681550126369004, 0.23382219808075316, 0.09306488684582744, 0.22056259718230223, 0.16368757447730473, 0.3323588401264575, 0.16791840658515336, 0.14363636363636362, 0.3570752036370525, 0.13617943378173014, 0.1457996489918881, 0.5197438633938101, 0.12393390191897662, 0.5069475571492604, 0.34157491152182456, 0.4373637984547315, 0.1724151313172473, 0.31948881789137384, 0.5584192439862543, 0.15750049280504633, 0.14259477895841535, 0),
 (5, 0.25883856311231007, 0.20257017247210005, 0.26798424435077045, 0.14150583244962886, 0.6786133429628961, 0.4619961965523588, 0.3697282099343955, 0.402037773359841, 0.5186868686868686, 0.5511794439764113, 0.08075321383306175, 0.11713224893917965, 0.06879329029826133, 0.0380800824806966, 0.19706292279974164, 0.23431069186168776, 0.09272727272727273, 0.21538170107974997, 0.19372994878144872, 0.14465956358912704, 0.2682319459267165, 0.312633262260128, 0.2639075651177848, 0.13674793550924108, 0.7127385590701975, 0.48278371219838756, 0.42771565495207664, 0.5982817869415809, 0.47703528484131685, 0.4549390003935459, 0),
 (6, 0.5333427989966397, 0.3473114643219479, 0.5238753368806579, 0.3802757158006363, 0.3791640335831002, 0.27489111097478686, 0.26405810684161196, 0.36779324055666, 0.3707070707070707, 0.1571187868576243, 0.12138330617418068, 0.09127475247524752, 0.11416859067992273, 0.08798688078775041, 0.0884182615494442, 0.08688076426232463, 0.05691919191919192, 0.1968175790869483, 0.08172454550571284, 0.04436659618865996, 0.5318392031305585, 0.41684434968017064, 0.5119278848548234, 0.3491938655131734, 0.4822690351977811, 0.2234479145443432, 0.3022364217252396, 0.663917525773196, 0.29528878375714573, 0.1878525514889152, 0),
 (7, 0.3184722419423542, 0.37605681433885685, 0.320710386289821, 0.1842629904559915, 0.5982666787036202, 0.4451260658855285, 0.21944704779756324, 0.2974652087475149, 0.5737373737373737, 0.5170598146588039, 0.17092160057939526, 0.2247171145685997, 0.1460208264618574, 0.08247696106447913, 0.2410850868545399, 0.21057770300718, 0.06282828282828283, 0.2742943739344573, 0.09818765126357853, 0.15606041761673783, 0.32479544646033437, 0.4296375266524521, 0.2997659245978385, 0.17494101454974437, 0.622267714455524, 0.33075258802184904, 0.21389776357827475, 0.5347079037800687, 0.32150601222156516, 0.3939393939393939, 0),
 (8, 0.2848691372047897, 0.40953669259384506, 0.3020523806233156, 0.15961823966065747, 0.6740994854202401, 0.5331574750015337, 0.43556701030927836, 0.4648608349900597, 0.6515151515151515, 0.5040016849199663, 0.07054137244251313, 0.14184052333804809, 0.0776987230834472, 0.03271958430924284, 0.13658768739164429, 0.24610208189383248, 0.08972222222222222, 0.23224095472627393, 0.1906343220577475, 0.09860702292608103, 0.2689434364994664, 0.49866737739872075, 0.27785248269336127, 0.13618265827762482, 0.6546258997556627, 0.4975308282640122, 0.4305111821086262, 0.7079037800687286, 0.5545042381233984, 0.3421225239407058, 0),
 (9, 0.259311846277628, 0.48461278322624274, 0.277658765807477, 0.1409968186638388, 0.5955583641780267, 0.6754800318998835, 0.5325679475164011, 0.42460238568588476, 0.48989898989898994, 0.6838668913226623, 0.06739091073691833, 0.27378005657708626, 0.060406163124911656, 0.03200983193810959, 0.1847911071829214, 0.5251149097245171, 0.19553030303030303, 0.27126349687440804, 0.140822873867282, 0.31733068004366877, 0.25471362504446815, 0.763859275053305, 0.2352706808107974, 0.12932559968541094, 0.7536815690418014, 1.0, 0.8825878594249201, 0.7594501718213059, 0.5521387739010448, 1.0, 0)]

#### 任务二：数据集的划分

In [89]:
%%sql

ALTER TABLE breast_cancer
ADD COLUMN random_number DOUBLE;

UPDATE breast_cancer
SET random_number = RAND();

 * mysql://stu2000017781:***@162.105.146.37:43306
0 rows affected.
569 rows affected.

[]

In [90]:
%%sql

ALTER TABLE breast_cancer
ADD COLUMN is_train BOOLEAN;

UPDATE breast_cancer
SET is_train = IF(random_number < 0.7, TRUE, FALSE);

 * mysql://stu2000017781:***@162.105.146.37:43306
0 rows affected.
569 rows affected.

[]

#### 任务三：实现KNN算法

In [91]:
%%sql

DROP TABLE IF EXISTS breast_cancer_distance;

CREATE TABLE breast_cancer_distance(
    id_from INT,
    id_to INT,
    distance DOUBLE,
    is_diagnosis BOOLEAN
)

 * mysql://stu2000017781:***@162.105.146.37:43306
0 rows affected.
0 rows affected.

[]

In [92]:
%%sql

# 计算测试集与训练集之间的距离
INSERT INTO breast_cancer_distance(id_from, id_to, distance, is_diagnosis)
SELECT bc1.id, bc2.id, SQRT(POW(bc1.radius_mean-bc2.radius_mean, 2) + POW(bc1.texture_mean-bc2.texture_mean, 2) + POW(bc1.perimeter_mean-bc2.perimeter_mean, 2) + 
    POW(bc1.area_mean-bc2.area_mean, 2) + POW(bc1.smoothness_mean-bc2.smoothness_mean, 2) + POW(bc1.compactness_mean-bc2.compactness_mean, 2) + POW(bc1.concavity_mean-bc2.concavity_mean, 2) 
    + POW(bc1.concave_points_mean-bc2.concave_points_mean, 2) + POW(bc1.symmetry_mean-bc2.symmetry_mean, 2) + POW(bc1.fractal_dimension_mean-bc2.fractal_dimension_mean, 2) + POW(bc1.radius_se-bc2.radius_se, 2)
    + POW(bc1.texture_se-bc2.texture_se, 2) + POW(bc1.perimeter_se-bc2.perimeter_se, 2) + POW(bc1.area_se-bc2.area_se, 2) + POW(bc1.smoothness_se-bc2.smoothness_se, 2) + POW(bc1.compactness_se-bc2.compactness_se, 2) + 
    POW(bc1.concavity_se-bc2.concavity_se, 2) + POW(bc1.concave_points_se-bc2.concave_points_se, 2) + POW(bc1.symmetry_se-bc2.symmetry_se, 2) + POW(bc1.fractal_dimension_se-bc2.fractal_dimension_se, 2) 
    + POW(bc1.radius_worst-bc2.radius_worst, 2) + POW(bc1.texture_worst-bc2.texture_worst, 2) + POW(bc1.perimeter_worst-bc2.perimeter_worst, 2) + POW(bc1.area_worst-bc2.area_worst, 2) + POW(bc1.smoothness_worst-bc2.smoothness_worst, 2) 
    + POW(bc1.compactness_worst-bc2.compactness_worst, 2) + POW(bc1.concavity_worst-bc2.concavity_worst, 2) + POW(bc1.concave_points_worst-bc2.concave_points_worst, 2) + POW(bc1.symmetry_worst-bc2.symmetry_worst, 2) + POW(bc1.fractal_dimension_worst-bc2.fractal_dimension_worst, 2) ) AS distance, bc2.diagnosis
FROM breast_cancer AS bc1, breast_cancer AS bc2
WHERE (NOT bc1.is_train) AND bc2.is_train

 * mysql://stu2000017781:***@162.105.146.37:43306
66420 rows affected.

[]

In [93]:
%%sql

SELECT * FROM breast_cancer_distance LIMIT 10;

 * mysql://stu2000017781:***@162.105.146.37:43306
10 rows affected.

[(551, 3, 2.0615665374362266, 0),
 (546, 3, 2.3673580363398194, 0),
 (541, 3, 1.797292671285451, 0),
 (537, 3, 1.7014808802258243, 0),
 (532, 3, 2.2821060246488094, 0),
 (531, 3, 1.9791727527006795, 0),
 (529, 3, 2.107046237852332, 0),
 (527, 3, 2.2488835842504864, 0),
 (526, 3, 1.9048131953122636, 0),
 (523, 3, 1.9123822621797186, 0)]

这里比较难受的一个点是因为当前的MySQL Server不支持LIMIT字句后面跟随一个变量， 因此我们后续选取K值只能手动选取。

In [94]:
%%sql

ALTER TABLE breast_cancer
ADD COLUMN predict_true BOOLEAN;

UPDATE breast_cancer
SET predict_true = IF(diagnosis = (SELECT is_diagnosis
FROM 
        (SELECT bcd.id_to, bcd.is_diagnosis
        FROM breast_cancer_distance AS bcd
        WHERE (breast_cancer.id = bcd.id_from)
        ORDER BY distance ASC
        LIMIT 13) as t
GROUP BY is_diagnosis
ORDER BY COUNT(*) DESC
LIMIT 1), TRUE, FALSE);

 * mysql://stu2000017781:***@162.105.146.37:43306
0 rows affected.
569 rows affected.

[]

In [95]:
%%sql

SELECT * FROM breast_cancer LIMIT 30;

 * mysql://stu2000017781:***@162.105.146.37:43306
30 rows affected.

[(0, 0.5210374366983767, 0.022658099425092997, 0.5459885287817012, 0.3637327677624602, 0.5937528211609642, 0.7920372983252562, 0.7031396438612932, 0.7311133200795229, 0.6863636363636364, 0.6055181128896379, 0.35614702154626104, 0.12046941301272983, 0.3690335956273854, 0.2738112581668217, 0.15929564537512322, 0.3513984438369334, 0.13568181818181818, 0.30062511839363515, 0.3116451848933416, 0.1830424388154167, 0.6207755247242974, 0.1415245202558635, 0.6683101748095025, 0.4506979944946913, 0.6011358383411478, 0.6192915563058473, 0.5686102236421725, 0.9120274914089348, 0.5984624482554701, 0.4188639643185098, 0, 0.9141323174481581, 0, 1),
 (1, 0.6431444933503716, 0.2725735542779844, 0.6157832907193699, 0.5015906680805938, 0.28987993138936535, 0.18176798969388383, 0.2036082474226804, 0.34875745526838964, 0.3797979797979798, 0.14132266217354678, 0.15643671917436175, 0.08258928571428571, 0.12444046553267682, 0.12565978953974424, 0.11938674915864973, 0.0813230390242437, 0.04696969696969697, 0.2538359537791249, 0.0845387516181685, 0.09111009770186422, 0.6069014585556741, 0.3035714285714286, 0.5398177200059765, 0.43521431380259534, 0.34755332496863234, 0.15456335923780692, 0.1929712460063898, 0.6391752577319588, 0.2335895919574217, 0.2228781319690411, 0, 0.71518206290452, 0, 1),
 (2, 0.6014955748024045, 0.39026039905309434, 0.5957432105590491, 0.4494167550371156, 0.5143089284102195, 0.4310165020550886, 0.46251171508903466, 0.6356858846918491, 0.5095959595959596, 0.21124684077506325, 0.22962158247329348, 0.09430251060820369, 0.18037035291900297, 0.16292178902423993, 0.15083115205493422, 0.28395469702887016, 0.09676767676767677, 0.38984656184883504, 0.20569032475938534, 0.1270055138675843, 0.5563856278904304, 0.3600746268656717, 0.5084416554609293, 0.3745084545812033, 0.48358977745492965, 0.38537512976491933, 0.35974440894568693, 0.8350515463917526, 0.40370589394835404, 0.21343303161484986, 0, 0.8335133929117707, 0, 1),
 (3, 0.21009039708457572, 0.36083868785931683, 0.23350148573008084, 0.10290562036055144, 0.8113207547169811, 0.8113612661799889, 0.5656044985941893, 0.5228628230616302, 0.7762626262626262, 1.0, 0.13909107369183413, 0.1758751768033946, 0.126655044055977, 0.03815479325660537, 0.2514532413230445, 0.5432150689458347, 0.14295454545454545, 0.3536654669444971, 0.7281476895367817, 0.28720478697676993, 0.24831020988971897, 0.3859275053304905, 0.2413466806115843, 0.09400806134486828, 0.9154724955424947, 0.814011700672352, 0.5486421725239616, 0.8848797250859107, 1.0, 0.773711137347501, 0, 0.022020806578938668, 1, 0),
 (4, 0.6298925647214729, 0.15657761244504562, 0.6309861101513371, 0.4892895015906681, 0.43035117811681867, 0.34789276731488866, 0.4639175257731959, 0.5183896620278331, 0.37828282828282833, 0.18681550126369004, 0.23382219808075316, 0.09306488684582744, 0.22056259718230223, 0.16368757447730473, 0.3323588401264575, 0.16791840658515336, 0.14363636363636362, 0.3570752036370525, 0.13617943378173014, 0.1457996489918881, 0.5197438633938101, 0.12393390191897662, 0.5069475571492604, 0.34157491152182456, 0.4373637984547315, 0.1724151313172473, 0.31948881789137384, 0.5584192439862543, 0.15750049280504633, 0.14259477895841535, 0, 0.609563884893026, 1, 0),
 (5, 0.25883856311231007, 0.20257017247210005, 0.26798424435077045, 0.14150583244962886, 0.6786133429628961, 0.4619961965523588, 0.3697282099343955, 0.402037773359841, 0.5186868686868686, 0.5511794439764113, 0.08075321383306175, 0.11713224893917965, 0.06879329029826133, 0.0380800824806966, 0.19706292279974164, 0.23431069186168776, 0.09272727272727273, 0.21538170107974997, 0.19372994878144872, 0.14465956358912704, 0.2682319459267165, 0.312633262260128, 0.2639075651177848, 0.13674793550924108, 0.7127385590701975, 0.48278371219838756, 0.42771565495207664, 0.5982817869415809, 0.47703528484131685, 0.4549390003935459, 0, 0.9817570354619595, 0, 1),
 (6, 0.5333427989966397, 0.3473114643219479, 0.5238753368806579, 0.3802757158006363, 0.3791640335831002, 0.27489111097478686, 0.26405810684161196, 0.36779324055666, 0.3707070707070707, 0.1571187868576243, 0.12138330617418068, 0.09127475247524752, 0.11416859067992273, 0.08798688078775041, 0.0884182615494442, 0.08688076426232463, 0.05691919191919192, 0.1968175790869483, 0.08172454550571284, 0.04436659618865996, 0.5318392031305585, 0.41684434968017064, 0.5119278848548234, 0.3491938655131734, 0.4822690351977811, 0.2234479145443432, 0.3022364217252396, 0.663917525773196, 0.29528878375714573, 0.1878525514889152, 0, 0.08009355336436401, 1, 0),
 (7, 0.3184722419423542, 0.37605681433885685, 0.320710386289821, 0.1842629904559915, 0.5982666787036202, 0.4451260658855285, 0.21944704779756324, 0.2974652087475149, 0.5737373737373737, 0.5170598146588039, 0.17092160057939526, 0.2247171145685997, 0.1460208264618574, 0.08247696106447913, 0.2410850868545399, 0.21057770300718, 0.06282828282828283, 0.2742943739344573, 0.09818765126357853, 0.15606041761673783, 0.32479544646033437, 0.4296375266524521, 0.2997659245978385, 0.17494101454974437, 0.622267714455524, 0.33075258802184904, 0.21389776357827475, 0.5347079037800687, 0.32150601222156516, 0.3939393939393939, 0, 0.45519669116958666, 1, 0),
 (8, 0.2848691372047897, 0.40953669259384506, 0.3020523806233156, 0.15961823966065747, 0.6740994854202401, 0.5331574750015337, 0.43556701030927836, 0.4648608349900597, 0.6515151515151515, 0.5040016849199663, 0.07054137244251313, 0.14184052333804809, 0.0776987230834472, 0.03271958430924284, 0.13658768739164429, 0.24610208189383248, 0.08972222222222222, 0.23224095472627393, 0.1906343220577475, 0.09860702292608103, 0.2689434364994664, 0.49866737739872075, 0.27785248269336127, 0.13618265827762482, 0.6546258997556627, 0.4975308282640122, 0.4305111821086262, 0.7079037800687286, 0.5545042381233984, 0.3421225239407058, 0, 0.03570282648848633, 1, 0),
 (9, 0.259311846277628, 0.48461278322624274, 0.277658765807477, 0.1409968186638388, 0.5955583641780267, 0.6754800318998835, 0.5325679475164011, 0.42460238568588476, 0.48989898989898994, 0.6838668913226623, 0.06739091073691833, 0.27378005657708626, 0.060406163124911656, 0.03200983193810959, 0.1847911071829214, 0.5251149097245171, 0.19553030303030303, 0.27126349687440804, 0.140822873867282, 0.31733068004366877, 0.25471362504446815, 0.763859275053305, 0.2352706808107974, 0.12932559968541094, 0.7536815690418014, 1.0, 0.8825878594249201, 0.7594501718213059, 0.5521387739010448, 1.0, 0, 0.8129240896673167, 0, 1),
 (10, 0.42780065313076815, 0.4575583361515048, 0.40709004215327205, 0.2775397667020148, 0.26568565496072943, 0.145113796699589, 0.07729615745079663, 0.16515904572564613, 0.23636363636363633, 0.1476411120471778, 0.09704870541372441, 0.18272630834512021, 0.08052584460255384, 0.06295877085831475, 0.07872998606248086, 0.052700754048126894, 0.027803030303030305, 0.14379617351771168, 0.09452918331738616, 0.0741815568729876, 0.4005691924582, 0.5826226012793179, 0.3655062503112705, 0.23712151002752652, 0.3099121706398996, 0.12400190160180843, 0.11653354632587859, 0.34278350515463923, 0.2726197516262567, 0.19336219336219337, 0, 0.9575119996047691, 0, 0),
 (11, 0.41644185716314075, 0.2766317213391951, 0.4133093773754405, 0.2704135737009544, 0.4014624898438206, 0.3368504999693271, 0.23322399250234302, 0.3283300198807157, 0.39494949494949494, 0.2287278854254423, 0.1427847184501177, 0.13806135077793494, 0.13226216840220517, 0.08845382313718018, 0.13794744535472686, 0.2880854387598763, 0.07047979797979798, 0.24284902443644632, 0.1716384307986717, 0.11225349971670608, 0.44432586268231955, 0.4067164179104478, 0.42875641217192095, 0.27374164372788046, 0.45189196328336523, 0.5177110923538143, 0.3166932907348243, 0.6219931271477663, 0.4389907352651291, 0.3263806900170537, 0, 0.34878775975554044, 1, 0),
 (12, 0.5768848502058783, 0.5103145079472439, 0.6123281044848318, 0.41548250265111347, 0.40417080436941416, 0.6944972701061285, 0.4838331771321462, 0.5556660039761432, 0.6752525252525251, 0.5905644481887111, 0.3056309976462067, 0.7089374115983027, 0.48593507044244455, 0.2043302365716719, 0.04847537138389366, 0.606227656442455, 0.2244949494949495, 0.77476794847509, 0.5200371475206843, 0.41268327736550453, 0.4635361081465671, 0.47761194029850756, 0.5044573932964789, 0.2818521431380259, 0.2148187281252064, 0.3521941186172638, 0.2906549520766773, 0.6072164948453609, 0.3175635718509758, 0.30998294634658274, 0, 0.8714028306970399, 0, 1),
 (13, 0.4197548393203654, 0.4815691579303347, 0.41400041462234816, 0.27113467656415696, 0.2832896993770877, 0.24789890190785843, 0.23284910965323335, 0.26660039761431414, 0.3974747474747475, 0.07203032855939341, 0.10566720984971935, 0.1586368458274399, 0.10111671300004713, 0.05561843712527876, 0.2738552537648299, 0.2178628293327726, 0.12755050505050505, 0.3773441939761319, 0.3085495581696403, 0.07279963517267113, 0.31696905016008536, 0.41684434968017064, 0.3067383833856268, 0.16990267400707823, 0.27689361421118674, 0.16019054826284793, 0.18546325878594247, 0.3845360824742268, 0.24521979105066033, 0.05135773317591498, 0, 0.3106509049522233, 1, 0),
 (14, 0.3194188082729898, 0.43625295908014877, 0.3442056526846797, 0.1844326617179215, 0.5459059312088111, 0.6438868781056377, 0.49859418931583876, 0.3988568588469185, 0.5095959595959596, 0.5657118786857624, 0.03642947673365924, 0.17874823196605374, 0.06144277434858408, 0.023175282686898346, 0.16031546384743514, 0.4289061795896297, 0.1389141414141414, 0.30839174086001137, 0.16502504643440083, 0.24868371958044858, 0.25257915332621844, 0.5327825159914712, 0.2908013347278251, 0.12595851356665355, 0.6202866010698012, 0.7230064712673787, 0.5545527156549521, 0.7587628865979382, 0.400354819633353, 0.5775941230486685, 0, 0.9390460634036418, 0, 1),
 (15, 0.3577547446637323, 0.6029759891782212, 0.36583511851288786, 0.21857900318133613, 0.5531281032770606, 0.4297895834611374, 0.384020618556701, 0.3660039761431412, 0.6277777777777778, 0.4382898062342039, 0.09360854608002896, 0.14869165487977365, 0.09998586439240446, 0.04809132645247086, 0.1323724377060883, 0.3015291254844234, 0.11972222222222222, 0.2064784997158553, 0.1503911746496313, 0.15792601191216507, 0.33902525791533267, 0.6692430703624735, 0.3670003486229394, 0.1862957137239481, 0.6381166215413062, 0.6116269367717397, 0.5611821086261981, 0.5883161512027492, 0.5229647151586833, 0.5185622458349731, 0, 0.7632776328951844, 0, 1),
 (16, 0.3643807089781817, 0.3523841731484612, 0.3520834772994264, 0.22948038176033933, 0.41563600252776023, 0.16140114103429237, 0.17326616682286786, 0.26138170974155067, 0.2656565656565656, 0.19502948609941037, 0.13079847908745246, 0.19443953323903818, 0.11487537105969937, 0.07209216321316105, 0.13614576605364243, 0.07035779733830023, 0.05045454545454545, 0.21007766622466376, 0.08749366803624696, 0.04111908019291628, 0.39630024902170047, 0.5026652452025586, 0.3635141192290453, 0.23417223751474633, 0.49679720002641486, 0.15504846173996564, 0.2327476038338658, 0.5529209621993127, 0.2885866351271437, 0.1778827233372688, 0, 0.9992500049986411, 0, 1),
 (17, 0.43300676794926407, 0.37098410551234356, 0.4444060534862829, 0.27796394485683984, 0.5811140200415277, 0.5607631433654376, 0.4034676663542643, 0.5109343936381711, 0.5575757575757576, 0.49705139005897225, 0.16574325547709579, 0.15753182461103252, 0.1459265890778872, 0.08849117852513456, 0.1806098514464425, 0.17092258238952146, 0.0805050505050505, 0.2456904716802425, 0.12675184330500364, 0.11218440363169024, 0.4635361081465671, 0.5186567164179106, 0.4302505104835899, 0.277674007078254, 0.7114178168130489, 0.38421088375973844, 0.38210862619808306, 0.7123711340206187, 0.4220382416715947, 0.3880362062180244, 0, 0.7064171570412975, 0, 1),
 (18, 0.607174972786218, 0.42069665201217443, 0.5957432105590491, 0.4735949098621421, 0.4123860250970479, 0.255567143120054, 0.3465323336457357, 0.4720675944333996, 0.26363636363636367, 0.08403538331929235, 0.234184320115879, 0.14515558698727013, 0.24068227865994443, 0.19723271286033942, 0.1625250705374443, 0.12525911016312674, 0.08563131313131313, 0.288122750520932, 0.07989531153261663, 0.03807885245222007, 0.6897901102810388, 0.5026652452025586, 0.6792668957617413, 0.5438458513566654, 0.5284950141979793, 0.2791376817921627, 0.42907348242811505, 0.820618556701031, 0.23713778829095208, 0.13846254755345663, 0, 0.534335800944209, 1, 0),
 (19, 0.31042642813195137, 0.15725397362191404, 0.3017759657245525, 0.1793425238600212, 0.4076916132526858, 0.18989632537881113, 0.15613870665417057, 0.23762425447316105, 0.4166666666666667, 0.16217354675652917, 0.057360130363932636, 0.09467821782178217, 0.06130141827262874, 0.03130007956697634, 0.22942516232110685, 0.09273890708084237, 0.06027777777777777, 0.2491002083727979, 0.16769854224123376, 0.04854690933211725, 0.2554251156172181, 0.19296375266524526, 0.2454803526072016, 0.12927644514353126, 0.48094829294063257, 0.145540452697655, 0.19089456869009583, 0.4426116838487973, 0.27833629016361133, 0.11511216056670605, 1, 0.5524275643307972, 1, 0),
 (20, 0.28865540252733213, 0.2029083530605343, 0.28912998410614327, 0.15970307529162248, 0.4953507267310644, 0.33010244770259495, 0.10702905342080599, 0.15457256461232605, 0.45808080808080814, 0.38226621735467575, 0.026688393988774213, 0.08563914427157002, 0.02949630118267917, 0.014695609621253722, 0.08104157459972124, 0.12563463213867276, 0.04287878787878787, 0.12293995074824779, 0.12520402994315302, 0.05286541464560619, 0.2337246531483458, 0.2257462686567164, 0.22750136959011907, 0.10944258749508455, 0.39642078848312756, 0.2428520146306915, 0.1509584664536741, 0.2502749140893471, 0.31914054799921154, 0.17571822117276664, 1, 0.15913044955500444, 1, 0),
 (21, 0.11940934260968337, 0.09232330064254307, 0.1143666643632092, 0.05531283138918345, 0.44930937979597374, 0.13968468192135455, 0.06925960637300843, 0.10318091451292247, 0.38131313131313127, 0.4020640269587195, 0.060039833423863834, 0.13627121640735504, 0.0542807331668473, 0.016619412100904372, 0.2683142400652684, 0.09063598401778472, 0.05012626262626262, 0.26917976889562417, 0.17431192660550457, 0.07162500172740215, 0.0818214158662398, 0.09701492537313436, 0.07331042382588775, 0.03187672040896578, 0.40434524202601857, 0.08490263992781676, 0.07082268370607028, 0.21398625429553267, 0.17445298639858073, 0.14882592155319427, 1, 0.13836958551627546, 1, 0),
 (22, 0.3956173978891571, 0.1538721677375718, 0.4057079676594568, 0.23792152704135736, 0.49354518371400213, 0.5954235936445617, 0.4866447985004686, 0.4848906560636183, 0.7378787878787879, 0.4288121314237573, 0.11852254209668658, 0.07721888260254597, 0.12378080384488527, 0.07117695620827869, 0.1725532855151783, 0.38324270736323496, 0.16277777777777777, 0.4265959462019322, 0.40578037935498396, 0.12089051034368395, 0.3607257203842049, 0.18816631130063965, 0.3719806763285024, 0.19556134486826582, 0.44792973651191975, 0.5511831650027651, 0.5035942492012779, 0.8223367697594502, 0.6114725014784153, 0.2913551095369278, 0, 0.21445660965000896, 1, 0),
 (23, 0.6710682001041224, 0.45079472438282037, 0.6454978923363969, 0.5346765641569459, 0.376004333303241, 0.2540334948776149, 0.257029053420806, 0.4290258449304175, 0.3580808080808081, 0.059393428812131485, 0.21010320478001082, 0.16946605374823195, 0.1670828817792018, 0.1628470782483311, 0.10249175646734882, 0.07764292366389282, 0.0433080808080808, 0.19662814927069522, 0.041481398097596656, 0.03773337202714095, 0.7556029882604056, 0.6281982942430705, 0.6852432890084168, 0.5971785292961069, 0.45519381892623656, 0.22577640655470502, 0.2519968051118211, 0.6903780068728522, 0.24778237729154348, 0.13262495080676898, 0, 0.6571743224348634, 1, 0),
 (24, 0.45761749254579015, 0.3946567467027392, 0.4575357611775275, 0.3228419936373277, 0.5368782161234993, 0.3874608919698178, 0.3573102155576382, 0.455765407554672, 0.47222222222222227, 0.28096040438079184, 0.2517834510229947, 0.11967379773691653, 0.22136361494604911, 0.17892857276269242, 0.14736376924907366, 0.12443296181692554, 0.06921717171717172, 0.2140556923659784, 0.09565486576236842, 0.06585547862858092, 0.6591960156527926, 0.5207889125799574, 0.6304596842472235, 0.49886944553676754, 0.721983754870237, 0.3206624559769479, 0.375, 0.7199312714776632, 0.40370589394835404, 0.26629935720844816, 0, 0.642501813957935, 1, 0),
 (25, 0.4808083676463629, 0.22624281366249568, 0.498997995991984, 0.3262778366914104, 0.5955583641780267, 0.6386724740813448, 0.5222586691658856, 0.6963220675944335, 1.0, 0.5090564448188711, 0.338403041825095, 0.13609441301272981, 0.3071667530509353, 0.19536494346262034, 0.21470578237073798, 0.2684080872412654, 0.09424242424242424, 0.4540632695586286, 0.21385152248550682, 0.22626203999281402, 0.5094272500889363, 0.25, 0.5079436226903731, 0.31355682265041285, 0.5502872614409298, 0.3566570616371239, 0.3077476038338658, 0.8762886597938145, 0.49300216834220384, 0.3335956972320609, 0, 0.24098613321873, 1, 0),
 (26, 0.3596478773250036, 0.39972945552925265, 0.37053417179185955, 0.21264050901378578, 0.4763925250519094, 0.513526777498313, 0.3338800374882849, 0.436530815109344, 0.602020202020202, 0.40606571187868573, 0.051783451022994746, 0.13768564356435645, 0.06375159025585449, 0.026611978378701454, 0.09310942652207907, 0.21253041728001926, 0.0677020202020202, 0.25610911157416183, 0.09368492148364946, 0.09729419731078039, 0.34471718249733196, 0.564765458422175, 0.3585337915234823, 0.17491643727880457, 0.5370798388694445, 0.6180302898002348, 0.4424121405750798, 0.9281786941580756, 0.532032328011039, 0.47527220254492986, 0, 0.27742525495348985, 1, 0),
 (27, 0.5503809929480808, 0.3564423402096719, 0.541151268053348, 0.4031813361611877, 0.3770876591134784, 0.26752959941107907, 0.34910965323336457, 0.38424453280318094, 0.3217171717171717, 0.14806234203875318, 0.26847727684229583, 0.329031117397454, 0.22970362342741366, 0.16200658201935755, 0.3072033178094299, 0.18752065370865506, 0.12830808080808082, 0.3620003788596325, 0.21174086790116506, 0.11477550681978362, 0.47598719316969046, 0.4061833688699361, 0.44568952637083525, 0.29930200550530867, 0.41359043782605825, 0.178915504846174, 0.27523961661341856, 0.5120274914089347, 0.15296668637886854, 0.1257378984651712, 0, 0.6641679058449044, 1, 0),
 (28, 0.39372426522788595, 0.5262089956036523, 0.40501693041254927, 0.2497985153764581, 0.5016701272907828, 0.46107600760689527, 0.3943298969072165, 0.43494035785288276, 0.43737373737373736, 0.325189553496209, 0.11859496650371175, 0.14405056577086278, 0.12915233473118787, 0.0685434013574948, 0.11965870075126625, 0.21268062607023763, 0.0903030303030303, 0.20515249100208374, 0.13786795744920358, 0.07159045368489422, 0.43898968338669514, 0.6580490405117272, 0.49250460680312774, 0.26636846244593, 0.6136828897840586, 0.5663183630701166, 0.5059904153354632, 0.69553264604811, 0.4853144096195545, 0.2867637413091959, 0, 0.4885637950976973, 1, 0),
 (29, 0.5011595437550287, 0.18058843422387555, 0.4920876235229079, 0.3442629904559915, 0.4138304595106979, 0.29544199742347094, 0.2313730084348641, 0.3952783300198808, 0.3429292929292929, 0.2428390901432183, 0.1770052507695093, 0.10217026166902404, 0.18366866135796073, 0.1014161427573506, 0.1330523166876296, 0.2108781205876168, 0.08603535353535353, 0.25648797120666794, 0.1599594754319806, 0.09836518662852564, 0.42974030594094637, 0.19989339019189767, 0.4207878878430201, 0.25604600865119936, 0.3587796341543948, 0.24634475264623418, 0.19880191693290736, 0.500343642611684, 0.2347723240685985, 0.1584022038567493, 0, 0.4503152886874185, 1, 0)]

In [96]:
%%sql

SET @num_sum = (SELECT COUNT(*) FROM breast_cancer WHERE NOT is_train);
SET @num_true = (SELECT COUNT(*) FROM breast_cancer WHERE predict_true AND (NOT is_train));

SELECT @num_true / @num_sum;

 * mysql://stu2000017781:***@162.105.146.37:43306
0 rows affected.
0 rows affected.
1 rows affected.

[(Decimal('0.9634'),)]

#### 任务四：讨论最佳K
下面我们将实验不同k值的结果，找出最优的k值。
正如前文所提到的，由于MySQL Server不支持LIMIT字句后面跟随一个变量，因此我们只能手动选取k值。为了节约篇幅，我们直接给出实验结果而不修改代码（实际上代码修改很简单，只需要修改LIMIT之后的常数即可）。
在knn中，我们一般选择k值为奇数来避免出现平票的情况，另一方面经验认为k=5效果比较好，综上我们选取了1,3,5,7,9,11,13这七个k值进行实验。

| K | 1 | 3 | 5 | 7 | 9 | 11 | 13 |
| :----: | :----: | :----: | :----: | :----: | :----: | :----: | :----: |
|Acurracy| 0.9630 | 0.9809 | 0.9706 | 0.9778 | 0.9632 | 0.9689 | 0.9634 |

可以看到在威斯康辛乳腺癌数据集上，当k=3时，准确率最高，为0.9809。

####

#### 与scikit-learn的结果对比
下面我们用scikit-learn中的KNN算法进行实验，与我们自己实现的KNN算法进行对比。

In [97]:
name = ['平均半径','平均纹理','平均周长','平均面积','平均光滑度',
        '平均紧凑度','平均凹度','平均凹点','平均对称','平均分形维数',
        '半径误差','纹理误差','周长误差','面积误差','平滑度误差',
        '紧凑度误差','凹度误差','凹点误差','对称误差','分形维数误差',
        '最差半径','最差纹理','最差的边界','最差的区域','最差的平滑度',
        '最差的紧凑性','最差的凹陷','最差的凹点','最差的对称性','最差的分形维数',
        '患病否']

breast_cancer = pd.DataFrame(np.concatenate((x,y.reshape(-1,1)),axis=1),columns=name)
breast_cancer.head()

,平均半径,平均纹理,平均周长,平均面积,平均光滑度,平均紧凑度,平均凹度,平均凹点,平均对称,平均分形维数,...,最差纹理,最差的边界,最差的区域,最差的平滑度,最差的紧凑性,最差的凹陷,最差的凹点,最差的对称性,最差的分形维数,患病否
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0.0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0.0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0.0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0.0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0.0

In [98]:
#划分训练集和测试集
from sklearn.model_selection import train_test_split 
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=420)

In [99]:
#归一化
from sklearn.preprocessing import MinMaxScaler as mms

mms_01 = mms().fit(xtrain) #求训练集最大/最小值
mms_02 = mms().fit(xtest) #求测试集最大/最小值

#转化
x_train = mms_01.transform(xtrain)
x_test = mms_02.transform(xtest)

In [104]:
#导入包
from sklearn.neighbors import KNeighborsClassifier

#建立模型
neighbors = [1, 3, 5, 7, 9, 11, 13]
for nn in neighbors:
    clf = KNeighborsClassifier(n_neighbors=nn)
    clf = clf.fit(x_train,ytrain)
    print(clf.score(x_test,ytest))

0.9415204678362573
0.9649122807017544
0.9766081871345029
0.9766081871345029
0.9766081871345029
0.9649122807017544
0.9707602339181286

scikit-learn中的KNN算法的结果如下：

| K | 1 | 3 | 5 | 7 | 9 | 11 | 13 |
| :----: | :----: | :----: | :----: | :----: | :----: | :----: | :----: |
|Acurracy| 0.9415 | 0.9649 | 0.9766 | 0.9766 | 0.9766 | 0.9649 | 0.9707 |

可以看到在威斯康辛乳腺癌数据集上，当k=5或7时，准确率最高，为0.9766。
总体来说，无论是scikit-learn中的knn算法还是我们自己使用SQL实现的knn,在预测的准确率上都十分相近，均位于0.96-0.98之间。这在一定程度上说明了我们自己用SQL实现的knn算法的正确性。